repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix, --exit-zero ] # --fix to automatically fix issues, --exit-zero to not fail the commit negligent of linting issues.
      # Run the formatter.
      - id: ruff-format